# -*- coding: utf-8 -*-

import unittest

from txtvz import BCVParser

class BCVParserTest(unittest.TestCase):
    p = None
    tokens = None

    def setUp(self):
        self.p = BCVParser()
        seg = self.p.parse('Genesis 1:1')
        print(seg.osis())

    def test_osis_simple(self):

        seg = self.p.parse('Genesis 1:1')
        x = seg.osis()

        #self.assertEqual(self.p.parse('Genesis 1:1'), "[S -> BCV, BCV -> BBOOK ('1', 'CD') (':', 'COL') ('1', 'CD'), BBOOK -> ('Genesis', 'GN')]")
        # self.assertEqual(self.p.parse('Gen 1:1').osis(), 'Gen1.1')
        # self.assertEqual(self.p.parse('Ge 1:1').osis(), 'Gen1.1')
        # self.assertEqual(self.p.parse('Gn 1:1').osis(), 'Gen1.1')
        # self.assertEqual(self.p.parse('Exodus 1:1').osis(), 'Exod1.1')
        # self.assertEqual(self.p.parse('Exo 1:1').osis(), 'Exod1.1')
        # self.assertEqual(self.p.parse('Ex 1:1').osis(), 'Exod1.1')
        # self.assertEqual(self.p.parse('Exod 1:1').osis(), 'Exod1.1')
        # self.assertEqual(self.p.parse('Leviticus 1:1').osis(), 'Lev1.1')
        # self.assertEqual(self.p.parse('Lev 1:1').osis(), 'Lev1.1')
        # self.assertEqual(self.p.parse('Le 1:1').osis(), 'Lev1.1')
        # self.assertEqual(self.p.parse('Lv 1:1').osis(), 'Lev1.1')
        # self.assertEqual(self.p.parse('Numbers 1:1').osis(), 'Num1.1')
        # self.assertEqual(self.p.parse('Num 1:1').osis(), 'Num1.1')
        # self.assertEqual(self.p.parse('Nu 1:1').osis(), 'Num1.1')
        # self.assertEqual(self.p.parse('Nm 1:1').osis(), 'Num1.1')
        # self.assertEqual(self.p.parse('Nb 1:1').osis(), 'Num1.1')
        # self.assertEqual(self.p.parse('Deuteronomy 1:1').osis(), 'Deut1.1')
        # self.assertEqual(self.p.parse('Deut 1:1').osis(), 'Deut1.1')
        # self.assertEqual(self.p.parse('Dt 1:1').osis(), 'Deut1.1')
        # self.assertEqual(self.p.parse('Joshua 1:1').osis(), 'Josh1.1')
        # self.assertEqual(self.p.parse('Josh 1:1').osis(), 'Josh1.1')
        # self.assertEqual(self.p.parse('Jos 1:1').osis(), 'Josh1.1')
        # self.assertEqual(self.p.parse('Jsh 1:1').osis(), 'Josh1.1')
        # self.assertEqual(self.p.parse('Judges 1:1').osis(), 'Judg1.1')
        # self.assertEqual(self.p.parse('Judg 1:1').osis(), 'Judg1.1')
        # self.assertEqual(self.p.parse('Jdg 1:1').osis(), 'Judg1.1')
        # self.assertEqual(self.p.parse('Jg 1:1').osis(), 'Judg1.1')
        # self.assertEqual(self.p.parse('Jdgs 1:1').osis(), 'Judg1.1')
        # self.assertEqual(self.p.parse('Ruth 1:1').osis(), 'Ruth1.1')
        # self.assertEqual(self.p.parse('Rth 1:1').osis(), 'Ruth1.1')
        # self.assertEqual(self.p.parse('Ru 1:1').osis(), 'Ruth1.1')
        # self.assertEqual(self.p.parse('1 Samuel 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1 Sam 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1 Sa 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1Samuel 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1S 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('I Sa 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1 Sm 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1Sa 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('I Sam 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1Sam 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('I Samuel 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('1st Samuel 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('First Samuel 1:1').osis(), '1Sam1.1')
        # self.assertEqual(self.p.parse('2 Samuel 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2 Sam 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2 Sa 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2S 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('II Sa 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2 Sm 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2Sa 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('II Sam 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2Sam 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('II Samuel 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2Samuel 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('2nd Samuel 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('Second Samuel 1:1').osis(), '2Sam1.1')
        # self.assertEqual(self.p.parse('1 Kings 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1 Kgs 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1 Ki 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1K 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('I Kgs 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1Kgs 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('I Ki 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1Ki 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('I Kings 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1Kings 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1st Kgs 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1st Kings 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('First Kings 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('First Kgs 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('1Kin 1:1').osis(), '1Kgs1.1')
        # self.assertEqual(self.p.parse('2 Kings 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2 Kgs 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2 Ki 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2K 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('II Kgs 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2Kgs 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('II Ki 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2Ki 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('II Kings 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2Kings 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2nd Kgs 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2nd Kings 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('Second Kings 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('Second Kgs 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('2Kin 1:1').osis(), '2Kgs1.1')
        # self.assertEqual(self.p.parse('1 Chronicles 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1 Chron 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1 Ch 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('I Ch 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1Ch 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1 Chr 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('I Chr 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1Chr 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('I Chron 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1Chron 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('I Chronicles 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1Chronicles 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('1st Chronicles 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('First Chronicles 1:1').osis(), '1Chr1.1')
        # self.assertEqual(self.p.parse('2 Chronicles 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2 Chron 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2 Ch 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('II Ch 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2Ch 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('II Chr 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2Chr 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('II Chron 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2Chron 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('II Chronicles 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2Chronicles 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('2nd Chronicles 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('Second Chronicles 1:1').osis(), '2Chr1.1')
        # self.assertEqual(self.p.parse('Ezra 1:1').osis(), 'Ezra1.1')
        # self.assertEqual(self.p.parse('Ezr 1:1').osis(), 'Ezra1.1')
        # self.assertEqual(self.p.parse('Nehemiah 1:1').osis(), 'Neh1.1')
        # self.assertEqual(self.p.parse('Neh 1:1').osis(), 'Neh1.1')
        # self.assertEqual(self.p.parse('Ne 1:1').osis(), 'Neh1.1')
        # self.assertEqual(self.p.parse('Esther 1:1').osis(), 'Esth1.1')
        # self.assertEqual(self.p.parse('Esth 1:1').osis(), 'Esth1.1')
        # self.assertEqual(self.p.parse('Es 1:1').osis(), 'Esth1.1')
        # self.assertEqual(self.p.parse('Job 1:1').osis(), 'Job1.1')
        # self.assertEqual(self.p.parse('Jb 1:1').osis(), 'Job1.1')
        # self.assertEqual(self.p.parse('Psalms 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Pslm 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Ps 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Psa 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Psm 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Pss 1:1').osis(), 'Ps1.1')
        # self.assertEqual(self.p.parse('Proverbs 1:1').osis(), 'Prov1.1')
        # self.assertEqual(self.p.parse('Prov 1:1').osis(), 'Prov1.1')
        # self.assertEqual(self.p.parse('Pr 1:1').osis(), 'Prov1.1')
        # self.assertEqual(self.p.parse('Prv 1:1').osis(), 'Prov1.1')
        # self.assertEqual(self.p.parse('Ecclesiastes 1:1').osis(), 'Eccl1.1')
        # self.assertEqual(self.p.parse('Eccles 1:1').osis(), 'Eccl1.1')
        # self.assertEqual(self.p.parse('Ec 1:1').osis(), 'Eccl1.1')
        # self.assertEqual(self.p.parse('Ecc 1:1').osis(), 'Eccl1.1')
        # self.assertEqual(self.p.parse('Qoh 1:1').osis(), 'Eccl1.1')
        # self.assertEqual(self.p.parse('Qoheleth 1:1').osis(), 'Eccl1.1')
        # # self.assertEqual(self.p.parse('Song of Solomon 1:1').osis()(), 'Song1.1')
        # self.assertEqual(self.p.parse('Song 1:1').osis(), 'Song1.1')
        # self.assertEqual(self.p.parse('So 1:1').osis(), 'Song1.1')
        # # self.assertEqual(self.p.parse('Canticle of Canticles 1:1').osis()(), 'Song1.1')
        # self.assertEqual(self.p.parse('Canticles 1:1').osis(), 'Song1.1')
        # # self.assertEqual(self.p.parse('Song of Songs 1:1').osis()(), 'Song1.1')
        # self.assertEqual(self.p.parse('SOS 1:1').osis(), 'Song1.1')
        # self.assertEqual(self.p.parse('Isaiah 1:1').osis(), 'Isa1.1')
        # self.assertEqual(self.p.parse('Isa 1:1').osis(), 'Isa1.1')
        # self.assertEqual(self.p.parse('Is 1:1').osis(), 'Isa1.1')
        # self.assertEqual(self.p.parse('Jeremiah 1:1').osis(), 'Jer1.1')
        # self.assertEqual(self.p.parse('Jer 1:1').osis(), 'Jer1.1')
        # self.assertEqual(self.p.parse('Je 1:1').osis(), 'Jer1.1')
        # self.assertEqual(self.p.parse('Jr 1:1').osis(), 'Jer1.1')
        # self.assertEqual(self.p.parse('Lamentations 1:1').osis(), 'Lam1.1')
        # self.assertEqual(self.p.parse('Lam 1:1').osis(), 'Lam1.1')
        # self.assertEqual(self.p.parse('La 1:1').osis(), 'Lam1.1')
        # self.assertEqual(self.p.parse('Ezekiel 1:1').osis(), 'Ezek1.1')
        # self.assertEqual(self.p.parse('Ezek 1:1').osis(), 'Ezek1.1')
        # self.assertEqual(self.p.parse('Eze 1:1').osis(), 'Ezek1.1')
        # self.assertEqual(self.p.parse('Ezk 1:1').osis(), 'Ezek1.1')
        # self.assertEqual(self.p.parse('Daniel 1:1').osis(), 'Dan1.1')
        # self.assertEqual(self.p.parse('Dan 1:1').osis(), 'Dan1.1')
        # self.assertEqual(self.p.parse('Da 1:1').osis(), 'Dan1.1')
        # self.assertEqual(self.p.parse('Dn 1:1').osis(), 'Dan1.1')
        # self.assertEqual(self.p.parse('Hosea 1:1').osis(), 'Hos1.1')
        # self.assertEqual(self.p.parse('Hos 1:1').osis(), 'Hos1.1')
        # self.assertEqual(self.p.parse('Ho 1:1').osis(), 'Hos1.1')
        # self.assertEqual(self.p.parse('Joel 1:1').osis(), 'Joel1.1')
        # self.assertEqual(self.p.parse('Joe 1:1').osis(), 'Joel1.1')
        # self.assertEqual(self.p.parse('Jl 1:1').osis(), 'Joel1.1')
        # self.assertEqual(self.p.parse('Amos 1:1').osis(), 'Amos1.1')
        # self.assertEqual(self.p.parse('Am 1:1').osis(), 'Amos1.1')
        # self.assertEqual(self.p.parse('Obadiah 1:1').osis(), 'Obad1.1')
        # self.assertEqual(self.p.parse('Obad 1:1').osis(), 'Obad1.1')
        # self.assertEqual(self.p.parse('Ob 1:1').osis(), 'Obad1.1')
        # self.assertEqual(self.p.parse('Jonah 1:1').osis(), 'Jonah1.1')
        # self.assertEqual(self.p.parse('Jnh 1:1').osis(), 'Jonah1.1')
        # self.assertEqual(self.p.parse('Jon 1:1').osis(), 'Jonah1.1')
        # self.assertEqual(self.p.parse('Micah 1:1').osis(), 'Mic1.1')
        # self.assertEqual(self.p.parse('Mic 1:1').osis(), 'Mic1.1')
        # self.assertEqual(self.p.parse('Nahum 1:1').osis(), 'Nah1.1')
        # self.assertEqual(self.p.parse('Nah 1:1').osis(), 'Nah1.1')
        # self.assertEqual(self.p.parse('Na 1:1').osis(), 'Nah1.1')
        # self.assertEqual(self.p.parse('Habakkuk 1:1').osis(), 'Hab1.1')
        # self.assertEqual(self.p.parse('Hab 1:1').osis(), 'Hab1.1')
        # self.assertEqual(self.p.parse('Zephaniah 1:1').osis(), 'Zeph1.1')
        # self.assertEqual(self.p.parse('Zeph 1:1').osis(), 'Zeph1.1')
        # self.assertEqual(self.p.parse('Zep 1:1').osis(), 'Zeph1.1')
        # self.assertEqual(self.p.parse('Zp 1:1').osis(), 'Zeph1.1')
        # self.assertEqual(self.p.parse('Haggai 1:1').osis(), 'Hag1.1')
        # self.assertEqual(self.p.parse('Hag 1:1').osis(), 'Hag1.1')
        # self.assertEqual(self.p.parse('Hg 1:1').osis(), 'Hag1.1')
        # self.assertEqual(self.p.parse('Zechariah 1:1').osis(), 'Zech1.1')
        # self.assertEqual(self.p.parse('Zech 1:1').osis(), 'Zech1.1')
        # self.assertEqual(self.p.parse('Zec 1:1').osis(), 'Zech1.1')
        # self.assertEqual(self.p.parse('Zc 1:1').osis(), 'Zech1.1')
        # self.assertEqual(self.p.parse('Malachi 1:1').osis(), 'Mal1.1')
        # self.assertEqual(self.p.parse('Mal 1:1').osis(), 'Mal1.1')
        # self.assertEqual(self.p.parse('Ml 1:1').osis(), 'Mal1.1')
        # self.assertEqual(self.p.parse('Tobit 1:1').osis()(), 'Tob1.1')
        # self.assertEqual(self.p.parse('Tob 1:1').osis()(), 'Tob1.1')
        # self.assertEqual(self.p.parse('Tb 1:1').osis()(), 'Tob1.1')
        # self.assertEqual(self.p.parse('Judith 1:1').osis()(), 'Jdt1.1')
        # self.assertEqual(self.p.parse('Jdth 1:1').osis()(), 'Jdt1.1')
        # self.assertEqual(self.p.parse('Jdt 1:1').osis()(), 'Jdt1.1')
        # self.assertEqual(self.p.parse('Jth 1:1').osis()(), 'Jdt1.1')
        # #self.assertEqual(self.p.parse('Wisdom of Solomon 1:1').osis()(), 'Wis1.1')
        # self.assertEqual(self.p.parse('Wisd of Sol 1:1').osis()(), 'Wis1.1')
        # self.assertEqual(self.p.parse('Wis 1:1').osis()(), 'Wis1.1')
        # self.assertEqual(self.p.parse('Ws 1:1').osis()(), 'Wis1.1')
        # self.assertEqual(self.p.parse('Wisdom 1:1').osis()(), 'Wis1.1')
        # self.assertEqual(self.p.parse('Sirach 1:1').osis()(), 'Sir1.1')
        # self.assertEqual(self.p.parse('Sir 1:1').osis()(), 'Sir1.1')
        # self.assertEqual(self.p.parse('Ecclesiasticus 1:1').osis()(), 'Sir1.1')
        # self.assertEqual(self.p.parse('Ecclus 1:1').osis()(), 'Sir1.1')
        # self.assertEqual(self.p.parse('Baruch 1:1').osis()(), 'Bar1.1')
        # self.assertEqual(self.p.parse('Bar 1:1').osis()(), 'Bar1.1')
        # self.assertEqual(self.p.parse('Letter of Jeremiah 1:1').osis()(), 'EpJer1.1')
        # self.assertEqual(self.p.parse('Let Jer 1:1').osis()(), 'EpJer1.1')
        # self.assertEqual(self.p.parse('LJe 1:1').osis()(), 'EpJer1.1')
        # self.assertEqual(self.p.parse('Ltr Jer 1:1').osis()(), 'EpJer1.1')
        # self.assertEqual(self.p.parse('Sus 1:1').osis()(), 'Sus1.1')
        # self.assertEqual(self.p.parse('Bel and the Dragon 1:1').osis()(), 'Bel1.1')
        # self.assertEqual(self.p.parse('1 Maccabees 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1 Macc 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1 Mac 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1M 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('I Ma 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1Ma 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('I Mac 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1Mac 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('I Macc 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1Macc 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('I Maccabees 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1Maccabees 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('1st Maccabees 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('First Maccabees 1:1').osis()(), '1Macc1.1')
        # self.assertEqual(self.p.parse('2 Maccabees 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2 Macc 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2 Mac 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2M 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('II Ma 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2Ma 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('II Mac 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2Mac 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('II Macc 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2Macc 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('II Maccabees 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2Maccabees 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('2nd Maccabees 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('Second Maccabees 1:1').osis()(), '2Macc1.1')
        # self.assertEqual(self.p.parse('1 Esdras 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1 Esdr 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1 Esd 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('I Es 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1Es 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('I Esd 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1Esd 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('I Esdr 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1Esdr 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('I Esdras 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1Esdras 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('1st Esdras 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('First Esdras 1:1').osis()(), '1Esd1.1')
        # self.assertEqual(self.p.parse('Prayer of Manasseh 1:1').osis()(), 'PrMan1.1')
        # self.assertEqual(self.p.parse('Pr of Man 1:1').osis()(), 'PrMan1.1')
        # self.assertEqual(self.p.parse('Pr Man 1:1').osis()(), 'PrMan1.1')
        # self.assertEqual(self.p.parse('PMa 1:1').osis()(), 'PrMan1.1')
        # self.assertEqual(self.p.parse('Prayer of Manasses 1:1').osis()(), 'PrMan1.1')
        # self.assertEqual(self.p.parse('3 Maccabees 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3 Macc 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3 Mac 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('III Ma 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3Ma 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('III Mac 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3Mac 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('III Macc 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3Macc 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('III Maccabees 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('3rd Maccabees 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('Third Maccabees 1:1').osis()(), '3Macc1.1')
        # self.assertEqual(self.p.parse('2 Esdras 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2 Esdr 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2 Esd 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('II Es 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2Es 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('II Esd 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2Esd 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('II Esdr 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2Esdr 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('II Esdras 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2Esdras 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('2nd Esdras 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('Second Esdras 1:1').osis()(), '2Esd1.1')
        # self.assertEqual(self.p.parse('4 Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4 Macc 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4 Mac 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('IV Ma 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4Ma 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('IV Mac 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4Mac 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('IV Macc 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4Macc 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('IV Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('IIII Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('4th Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('Fourth Maccabees 1:1').osis()(), '4Macc1.1')
        # self.assertEqual(self.p.parse('Matthew 1:1').osis(), 'Matt1.1')
        # self.assertEqual(self.p.parse('Matt 1:1').osis(), 'Matt1.1')
        # self.assertEqual(self.p.parse('Mt 1:1').osis(), 'Matt1.1')
        # self.assertEqual(self.p.parse('Mark 1:1').osis(), 'Mark1.1')
        # self.assertEqual(self.p.parse('Mrk 1:1').osis(), 'Mark1.1')
        # self.assertEqual(self.p.parse('Mk 1:1').osis(), 'Mark1.1')
        # self.assertEqual(self.p.parse('Mr 1:1').osis(), 'Mark1.1')
        # self.assertEqual(self.p.parse('Luke 1:1').osis(), 'Luke1.1')
        # self.assertEqual(self.p.parse('Luk 1:1').osis(), 'Luke1.1')
        # self.assertEqual(self.p.parse('Lk 1:1').osis(), 'Luke1.1')
        # self.assertEqual(self.p.parse('John 1:1').osis(), 'John1.1')
        # self.assertEqual(self.p.parse('Jn 1:1').osis(), 'John1.1')
        # self.assertEqual(self.p.parse('Jhn 1:1').osis(), 'John1.1')
        # self.assertEqual(self.p.parse('Acts 1:1').osis(), 'Acts1.1')
        # self.assertEqual(self.p.parse('Ac 1:1').osis(), 'Acts1.1')
        # self.assertEqual(self.p.parse('Romans 1:1').osis(), 'Rom1.1')
        # self.assertEqual(self.p.parse('Rom 1:1').osis(), 'Rom1.1')
        # self.assertEqual(self.p.parse('Ro 1:1').osis(), 'Rom1.1')
        # self.assertEqual(self.p.parse('Rm 1:1').osis(), 'Rom1.1')
        # self.assertEqual(self.p.parse('1 Corinthians 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1 Cor 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1 Co 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('I Co 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1Co 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('I Cor 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1Cor 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('I Corinthians 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1Corinthians 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('1st Corinthians 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('First Corinthians 1:1').osis(), '1Cor1.1')
        # self.assertEqual(self.p.parse('2 Corinthians 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2 Cor 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2 Co 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('II Co 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2Co 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('II Cor 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2Cor 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('II Corinthians 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2Corinthians 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('2nd Corinthians 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('Second Corinthians 1:1').osis(), '2Cor1.1')
        # self.assertEqual(self.p.parse('Galatians 1:1').osis(), 'Gal1.1')
        # self.assertEqual(self.p.parse('Gal 1:1').osis(), 'Gal1.1')
        # self.assertEqual(self.p.parse('Ga 1:1').osis(), 'Gal1.1')
        # self.assertEqual(self.p.parse('Ephesians 1:1').osis(), 'Eph1.1')
        # self.assertEqual(self.p.parse('Ephes 1:1').osis(), 'Eph1.1')
        # self.assertEqual(self.p.parse('Eph 1:1').osis(), 'Eph1.1')
        # self.assertEqual(self.p.parse('Philippians 1:1').osis(), 'Phil1.1')
        # self.assertEqual(self.p.parse('Phil 1:1').osis(), 'Phil1.1')
        # self.assertEqual(self.p.parse('Php 1:1').osis(), 'Phil1.1')
        # self.assertEqual(self.p.parse('Colossians 1:1').osis(), 'Col1.1')
        # self.assertEqual(self.p.parse('Col 1:1').osis(), 'Col1.1')
        # self.assertEqual(self.p.parse('1 Thessalonians 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1 Thess 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1 Th 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('I Th 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1Th 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('I Thes 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1Thes 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('I Thess 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1Thess 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('I Thessalonians 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1Thessalonians 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('1st Thessalonians 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('First Thessalonians 1:1').osis(), '1Thess1.1')
        # self.assertEqual(self.p.parse('2 Thessalonians 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2 Thess 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2 Th 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('II Th 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2Th 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('II Thes 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2Thes 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('II Thess 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2Thess 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('II Thessalonians 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2Thessalonians 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('2nd Thessalonians 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('Second Thessalonians 1:1').osis(), '2Thess1.1')
        # self.assertEqual(self.p.parse('1 Timothy 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1 Tim 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1 Ti 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('I Ti 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1Ti 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('I Tim 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1Tim 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('I Timothy 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1Timothy 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('1st Timothy 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('First Timothy 1:1').osis(), '1Tim1.1')
        # self.assertEqual(self.p.parse('2 Timothy 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2 Tim 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2 Ti 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('II Ti 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2Ti 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('II Tim 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2Tim 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('II Timothy 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2Timothy 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('2nd Timothy 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('Second Timothy 1:1').osis(), '2Tim1.1')
        # self.assertEqual(self.p.parse('Titus 1:1').osis(), 'Titus1.1')
        # self.assertEqual(self.p.parse('Tit 1:1').osis(), 'Titus1.1')
        # self.assertEqual(self.p.parse('Philemon 1:1').osis(), 'Phlm1.1')
        # self.assertEqual(self.p.parse('Philem 1:1').osis(), 'Phlm1.1')
        # self.assertEqual(self.p.parse('Phm 1:1').osis(), 'Phlm1.1')
        # self.assertEqual(self.p.parse('Hebrews 1:1').osis(), 'Heb1.1')
        # self.assertEqual(self.p.parse('Heb 1:1').osis(), 'Heb1.1')
        # self.assertEqual(self.p.parse('James 1:1').osis(), 'Jas1.1')
        # self.assertEqual(self.p.parse('Jas 1:1').osis(), 'Jas1.1')
        # self.assertEqual(self.p.parse('Jm 1:1').osis(), 'Jas1.1')
        # self.assertEqual(self.p.parse('1 Peter 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1 Pet 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1 Pe 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('I Pe 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1Pe 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('I Pet 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1Pet 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('I Pt 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1 Pt 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1Pt 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('I Peter 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1Peter 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('1st Peter 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('First Peter 1:1').osis(), '1Pet1.1')
        # self.assertEqual(self.p.parse('2 Peter 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2 Pet 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2 Pe 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('II Pe 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2Pe 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('II Pet 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2Pet 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('II Pt 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2 Pt 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2Pt 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('II Peter 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2Peter 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('2nd Peter 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('Second Peter 1:1').osis(), '2Pet1.1')
        # self.assertEqual(self.p.parse('1 John 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1 Jn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('I Jn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1Jn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('I Jo 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1Jo 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('I Joh 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1Joh 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('I Jhn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1 Jhn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1Jhn 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('I John 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1John 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('1st John 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('First John 1:1').osis(), '1John1.1')
        # self.assertEqual(self.p.parse('2 John 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2 Jn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('II Jn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2Jn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('II Jo 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2Jo 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('II Joh 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2Joh 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('II Jhn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2 Jhn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2Jhn 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('II John 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2John 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('2nd John 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('Second John 1:1').osis(), '2John1.1')
        # self.assertEqual(self.p.parse('3 John 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3 Jn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('III Jn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3Jn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('III Jo 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3Jo 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('III Joh 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3Joh 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('III Jhn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3 Jhn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3Jhn 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('III John 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3John 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('3rd John 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('Third John 1:1').osis(), '3John1.1')
        # self.assertEqual(self.p.parse('Jude 1:1').osis(), 'Jude1.1')
        # self.assertEqual(self.p.parse('Jud 1:1').osis(), 'Jude1.1')
        # self.assertEqual(self.p.parse('Revelation 1:1').osis(), 'Rev1.1')
        # self.assertEqual(self.p.parse('Rev 1:1').osis(), 'Rev1.1')
        # self.assertEqual(self.p.parse('Re 1:1').osis(), 'Rev1.1')
        # self.assertEqual(self.p.parse('The Revelation 1:1').osis(), 'Rev1.1')

    # def test_osis_cont(self):
    #     print ("Cont")
    #     print(self.p.parse('Genesis 1:1-2'))
    #     self.assertEqual(self.p.parse('Genesis 1:1-2'), '(S (BCV (BBOOK Genesis/GN) 1/CD :/COL 1/CD) -/THRU 2/CD)')

if __name__ == '__main__':
    unittest.main()
